# Generated by Django 4.0.6 on 2023-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_rename_quantity_cart_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
